# Site Specific Configuration
title: nathan dixon
description: my personal site.
url: https://nathandixon.dev
author: nateJDXN
timezone: America/New York
timezone_short: EST

# Keywords
keywords: ['seo', 'key', 'words']

# Analytics (Plausible requires sign-up)
analytics:
  plausible:
    enabled: false
    site_fqdn: 'your.site.fqdn'
    script_source: 'https://plausible.io/js/script.js'

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  # Value set low for demonstration purposes
  per_page: 3
  sort_field: 'date'
  sort_reverse: true

# Category Paginating
autopages:
  enabled: true
  categories:
    title: 'Posts in category :general'
    permalink: '/category/:general'
    silent: false

# Exclusions
exclude: [ 'README.md' ]

# Plugins
gems:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

